# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'wm.ui'
##
## Created by: Qt User Interface Compiler version 6.10.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QToolBar,
    QWidget)

from qcustomplot import QCustomPlot

class Ui_WM(object):
    def setupUi(self, WM):
        if not WM.objectName():
            WM.setObjectName(u"WM")
        WM.resize(1515, 969)
        self.centralWidget = QWidget(WM)
        self.centralWidget.setObjectName(u"centralWidget")
        self.pushButton_open_com = QPushButton(self.centralWidget)
        self.pushButton_open_com.setObjectName(u"pushButton_open_com")
        self.pushButton_open_com.setGeometry(QRect(40, 0, 94, 27))
        self.pushButton_open_pulser = QPushButton(self.centralWidget)
        self.pushButton_open_pulser.setObjectName(u"pushButton_open_pulser")
        self.pushButton_open_pulser.setGeometry(QRect(40, 0, 94, 27))
        self.pushButton_open_osc = QPushButton(self.centralWidget)
        self.pushButton_open_osc.setObjectName(u"pushButton_open_osc")
        self.pushButton_open_osc.setGeometry(QRect(170, 0, 94, 27))
        self.pushButton_open_pm = QPushButton(self.centralWidget)
        self.pushButton_open_pm.setObjectName(u"pushButton_open_pm")
        self.pushButton_open_pm.setGeometry(QRect(300, 0, 94, 27))
        self.comboBox_port = QComboBox(self.centralWidget)
        self.comboBox_port.setObjectName(u"comboBox_port")
        self.comboBox_port.setGeometry(QRect(410, 0, 160, 27))
        self.pushButton_refresh_ports = QPushButton(self.centralWidget)
        self.pushButton_refresh_ports.setObjectName(u"pushButton_refresh_ports")
        self.pushButton_refresh_ports.setGeometry(QRect(575, 0, 27, 27))
        self.customPlot = QCustomPlot(self.centralWidget)
        self.customPlot.setObjectName(u"customPlot")
        self.customPlot.setGeometry(QRect(10, 30, 1131, 781))
        self.groupBox = QGroupBox(self.centralWidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QRect(1150, 10, 271, 801))
        self.pushButton_save_data = QPushButton(self.groupBox)
        self.pushButton_save_data.setObjectName(u"pushButton_save_data")
        self.pushButton_save_data.setGeometry(QRect(10, 560, 251, 141))
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pushButton_save_data.setFont(font)
        self.spinBox_HV_n_from = QSpinBox(self.groupBox)
        self.spinBox_HV_n_from.setObjectName(u"spinBox_HV_n_from")
        self.spinBox_HV_n_from.setGeometry(QRect(80, 200, 81, 25))
        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(True)
        self.spinBox_HV_n_from.setFont(font1)
        self.spinBox_HV_n_from.setMinimum(1)
        self.spinBox_HV_n_from.setMaximum(4095)
        self.spinBox_HV_n_from.setValue(1)
        self.spinBox_HV_n_from.setDisplayIntegerBase(10)
        self.label_power = QLabel(self.groupBox)
        self.label_power.setObjectName(u"label_power")
        self.label_power.setGeometry(QRect(160, 350, 91, 20))
        self.label_power.setFont(font1)
        self.label_hv = QLabel(self.groupBox)
        self.label_hv.setObjectName(u"label_hv")
        self.label_hv.setGeometry(QRect(20, 378, 231, 20))
        self.label_hv.setFont(font)
        self.pushButton_start = QPushButton(self.groupBox)
        self.pushButton_start.setObjectName(u"pushButton_start")
        self.pushButton_start.setGeometry(QRect(10, 30, 251, 141))
        font2 = QFont()
        font2.setPointSize(21)
        font2.setBold(True)
        self.pushButton_start.setFont(font2)
        self.pushButton_start.setFlat(False)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(100, 180, 121, 20))
        self.label_6.setFont(font1)
        self.label_current = QLabel(self.groupBox)
        self.label_current.setObjectName(u"label_current")
        self.label_current.setGeometry(QRect(160, 325, 91, 20))
        self.label_current.setFont(font1)
        self.spinBox_HV_b = QSpinBox(self.groupBox)
        self.spinBox_HV_b.setObjectName(u"spinBox_HV_b")
        self.spinBox_HV_b.setGeometry(QRect(180, 240, 41, 25))
        self.spinBox_HV_b.setFont(font1)
        self.spinBox_HV_b.setMinimum(1)
        self.spinBox_HV_b.setMaximum(2)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 325, 121, 20))
        self.label.setFont(font)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 350, 131, 20))
        self.label_3.setFont(font)
        self.checkBox_laser_on = QCheckBox(self.groupBox)
        self.checkBox_laser_on.setObjectName(u"checkBox_laser_on")
        self.checkBox_laser_on.setGeometry(QRect(80, 750, 131, 41))
        self.checkBox_laser_on.setFont(font1)
        self.pushButton_stop = QPushButton(self.groupBox)
        self.pushButton_stop.setObjectName(u"pushButton_stop")
        self.pushButton_stop.setEnabled(False)
        self.pushButton_stop.setGeometry(QRect(10, 410, 251, 141))
        self.pushButton_stop.setFont(font2)
        self.pushButton_stop.setFlat(False)
        self.spinBox_HV_n_to = QSpinBox(self.groupBox)
        self.spinBox_HV_n_to.setObjectName(u"spinBox_HV_n_to")
        self.spinBox_HV_n_to.setGeometry(QRect(80, 240, 81, 25))
        self.spinBox_HV_n_to.setFont(font1)
        self.spinBox_HV_n_to.setMinimum(1)
        self.spinBox_HV_n_to.setMaximum(4095)
        self.spinBox_HV_n_to.setValue(4095)
        self.spinBox_HV_n_to.setDisplayIntegerBase(10)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 200, 58, 21))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 240, 58, 21))
        self.spinBox_HV_n_step = QSpinBox(self.groupBox)
        self.spinBox_HV_n_step.setObjectName(u"spinBox_HV_n_step")
        self.spinBox_HV_n_step.setGeometry(QRect(80, 280, 81, 25))
        self.spinBox_HV_n_step.setFont(font1)
        self.spinBox_HV_n_step.setMinimum(1)
        self.spinBox_HV_n_step.setMaximum(500)
        self.spinBox_HV_n_step.setValue(100)
        self.spinBox_HV_n_step.setDisplayIntegerBase(10)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 280, 58, 21))
        self.pushButton_clear_data = QPushButton(self.centralWidget)
        self.pushButton_clear_data.setObjectName(u"pushButton_clear_data")
        self.pushButton_clear_data.setGeometry(QRect(1020, 0, 94, 27))
        WM.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(WM)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1515, 30))
        WM.setMenuBar(self.menuBar)
        self.mainToolBar = QToolBar(WM)
        self.mainToolBar.setObjectName(u"mainToolBar")
        WM.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.mainToolBar)
        self.statusBar = QStatusBar(WM)
        self.statusBar.setObjectName(u"statusBar")
        WM.setStatusBar(self.statusBar)

        self.retranslateUi(WM)

        QMetaObject.connectSlotsByName(WM)
    # setupUi

    def retranslateUi(self, WM):
        WM.setWindowTitle(QCoreApplication.translate("WM", u"WM", None))
        self.pushButton_open_com.setText(QCoreApplication.translate("WM", u"connect com", None))
        self.pushButton_open_pulser.setText(QCoreApplication.translate("WM", u"connect pulser", None))
        self.pushButton_open_osc.setText(QCoreApplication.translate("WM", u"connect osc", None))
        self.pushButton_open_pm.setText(QCoreApplication.translate("WM", u"connect PM", None))
        self.pushButton_refresh_ports.setText(QCoreApplication.translate("WM", u"\u21ba", None))
#if QT_CONFIG(tooltip)
        self.pushButton_refresh_ports.setToolTip(QCoreApplication.translate("WM", u"Refresh serial port list", None))
#endif // QT_CONFIG(tooltip)
        self.groupBox.setTitle(QCoreApplication.translate("WM", u"...", None))
        self.pushButton_save_data.setText(QCoreApplication.translate("WM", u"Save data", None))
        self.label_power.setText(QCoreApplication.translate("WM", u"0.00", None))
        self.label_hv.setText(QCoreApplication.translate("WM", u"HV: \u2014", None))
        self.pushButton_start.setText(QCoreApplication.translate("WM", u"Start", None))
        self.label_6.setText(QCoreApplication.translate("WM", u"n              b", None))
        self.label_current.setText(QCoreApplication.translate("WM", u"0.00", None))
        self.label.setText(QCoreApplication.translate("WM", u"Current, A:", None))
        self.label_3.setText(QCoreApplication.translate("WM", u"Power, mW", None))
        self.checkBox_laser_on.setText(QCoreApplication.translate("WM", u"laser ON", None))
        self.pushButton_stop.setText(QCoreApplication.translate("WM", u"Stop", None))
        self.label_2.setText(QCoreApplication.translate("WM", u"from", None))
        self.label_4.setText(QCoreApplication.translate("WM", u"to", None))
        self.label_5.setText(QCoreApplication.translate("WM", u"step", None))
        self.pushButton_clear_data.setText(QCoreApplication.translate("WM", u"clear data", None))
    # retranslateUi

